name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Deploy'
    runs-on: ubuntu-latest

    env:
      DRY_RUN: false
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      CLOUD_ID: ${{ secrets.CLOUD_ID }}
      FOLDER_ID: ${{ secrets.FOLDER_ID }}
      S3TF_ACCESS_KEY: ${{ secrets.S3TF_ACCESS_KEY }}
      S3TF_SECRET_KEY: ${{ secrets.S3TF_SECRET_KEY }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install s3cmd
        run: |
          python -m pip install --upgrade pip
          pip install s3cmd
          cat env/dev/s3cfg.tmpl > ~/.s3cfg
          echo "access_key=$S3TF_ACCESS_KEY" >> ~/.s3cfg
          echo "secret_key=$S3TF_SECRET_KEY" >> ~/.s3cfg
      - name: 'Terraform Init'
        working-directory: terraform
        run: |
          terraform init -var-file="../env/dev/env.tfvars"
          terraform validate
      - name: Check and download file from S3
        working-directory: terraform
        continue-on-error: true
        run: |
          s3cmd ls s3://s3tfstate/infra.tfstate || { echo "File does not exist."; exit 0; }
          s3cmd get s3://s3tfstate/infra.tfstate terraform.tfstate
      # - name: 'Terraform Plan'
      #   working-directory: terraform
      #   id: plan
      #   run: |
      #     terraform plan -var "yc_oauth_token=${{ env.YC_TOKEN }}" \
      #       -var "cloud_id=${{ env.CLOUD_ID }}" -var "folder_id=${{ env.FOLDER_ID }}" \
      #       -var-file="../env/dev/env.tfvars" -out=infra.tfplan -input=false -detailed-exitcode
      #   continue-on-error: true
      # - name: 'Check Plan Exit Code'
      #   id: check_plan
      #   run: |
      #     if [[ ${{ steps.plan.outcome }} == 'success' ]]; then
      #       echo "apply_required=false" >> $GITHUB_ENV
      #     elif [[ ${{ steps.plan.outcome }} == 'failure' ]]; then
      #       exit 1
      #     else
      #       echo "apply_required=true" >> $GITHUB_ENV
      #     fi

      # - name: Terraform Apply
      #   working-directory: terraform
      #   if: env.apply_required == 'true' && env.DRY_RUN == 'false'
      #   run: |
      #     set -xe
      #     terraform apply -var "yc_oauth_token=${{ env.YC_TOKEN }}" \
      #       -var "cloud_id=${{ env.CLOUD_ID }}" -var "folder_id=${{ env.FOLDER_ID }}" \
      #       -var-file="../env/dev/env.tfvars" -auto-approve
      - name: 'Terraform Plan'
        working-directory: terraform
        id: plan
        run: |
          terraform plan -var "yc_oauth_token=${{ env.YC_TOKEN }}" \
            -var "cloud_id=${{ env.CLOUD_ID }}" -var "folder_id=${{ env.FOLDER_ID }}" \
            -var-file="../env/dev/env.tfvars" -out=infra.tfplan -input=false -detailed-exitcode
      - name: Terraform Apply
        working-directory: terraform
        run: |
          set -xe
          terraform apply -var "yc_oauth_token=${{ env.YC_TOKEN }}" \
            -var "cloud_id=${{ env.CLOUD_ID }}" -var "folder_id=${{ env.FOLDER_ID }}" \
            -var-file="../env/dev/env.tfvars" -auto-approve
      - name: Check and download file from S3
        working-directory: terraform
        if: env.DRY_RUN != 'true'
        continue-on-error: true
        run: |
          ls terraform.tfstate || { echo "Local TF state does not exist."; exit 0; }
          s3cmd put terraform.tfstate s3://s3tfstate/infra.tfstate