name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Deploy'
    runs-on: ubuntu-latest

    env:
      DRY_RUN: true
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      CLOUD_ID: ${{ secrets.CLOUD_ID }}
      FOLDER_ID: ${{ secrets.FOLDER_ID }}
      S3TF_ACCESS_KEY: ${{ secrets.S3TF_ACCESS_KEY }}
      S3TF_SECRET_KEY: ${{ secrets.S3TF_SECRET_KEY }}

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install s3cmd
        run: |
          python -m pip install --upgrade pip
          pip install s3cmd
          cat env/dev/s3cfg.tmpl > $HOME/.s3cfg
          echo "access_key=$S3TF_ACCESS_KEY" >> $HOME/.s3cfg
          echo "secret_key=$S3TF_SECRET_KEY" >> $HOME/.s3cfg
          s3cmd ls
      - name: 'Terraform Init'
        working-directory: terraform
        run: |
          terraform init -var-file="../env/dev/env.tfvars"
          terraform validate

      - name: 'Terraform Plan'
        working-directory: terraform
        run: |
          set -xe
          env | sort
          # terraform plan -var "yc_oauth_token=${{ env.YC_TOKEN }}" \
          #   -var "cloud_id=${{ env.CLOUD_ID }}" -var "folder_id=${{ env.FOLDER_ID }}" \
          #   -var-file="../env/dev/env.tfvars" -out=infra.tfplan
      # - name: 'Dry Run Check'
      #   if: env.DRY_RUN == 'true'
      #   run: |
      #     echo "Dry Run: Skipping deployment steps."

      # - name: 'Terraform Apply'
      #   working-directory: terraform
      #   if: env.DRY_RUN != 'true'
      #   run: |
      #     set -xe
      #     terraform apply -var "yc_oauth_token=${{ env.YC_TOKEN }}" \
      #       -var "cloud_id=${{ env.CLOUD_ID }}" -var "folder_id=${{ env.FOLDER_ID }}" \
      #       -var-file="../env/dev/env.tfvars" -auto-approve